adds check on filenames to banned-characters rule
mgechev/revive pull request #1091
Opened 2024-10-30 12:29 UTC by chavacava

Closes #1090 by adding filename checks to the `banned-characters` rule.

2024-10-30 12:58 UTC, denisvmedia approved these changes
Lgtm 👍

2024-10-30 19:38 UTC, ccoVeille requested changes
For me, it should be a separate rule

The banned characters list won't be used for the file names

People might want to add other rules by extending the rules such as no space, no hypen, lowercase only, to respect the Go convention

Linting files is a good thing, but it should be separate.

2024-10-30 23:16 UTC, chavacava commented
@ccoVeille I've created the PR #1092 that adds the rule.

The rule, of course, accepts a regular expression. Like that, it anticipates people clamor for regular expressions everywhere. 

> to respect the Go convention

there is not such a convention. Check https://github.com/golang/go/issues/36060

2024-11-02 09:36 UTC, ccoVeille commented
There is indeed no convention, but a common practice inherited from package name convention.

Anyway it's great you opened the other PR

But then, shouldn't this one be simply closed?

2024-11-02 17:24 UTC, chavacava commented
replaced by #1092

2024-11-02 17:24 UTC, closed without merging