Update GoReleaser configuration
mgechev/revive pull request #1105
Opened 2024-11-10 00:42 UTC by morphy2k

This PR updates the GoReleaser configuration to v2. It also fixes the setting of the version variables and introduces other small improvements.

Additionally, I have removed the i386 architecture, as I don't think any developer is using it these days.

2024-11-11 11:06 UTC, alexandear requested changes

2024-11-11 11:06 UTC, alexandear commented on .goreleaser.yml
> +    - go generate ./...
Can we revert style changes that are not related to the topic of the PR?

2024-11-11 11:08 UTC, alexandear commented on .goreleaser.yml
> +    - go generate ./...
I propose to create two PRs:

1) the fix for https://github.com/mgechev/revive/issues/1104
2) the PR for updating GoReleaser configuration.

2024-11-14 09:15 UTC, alexandear approved these changes

2024-11-14 09:16 UTC, alexandear commented
This PR fixes #1104?

2024-12-13 10:43 UTC, merged

2024-12-13 10:43 UTC, denisvmedia commented
Thank you!