fix #751 [rule.add-constant] add ignoreFuncs to exclude constants in …
mgechev/revive pull request #756
Opened 2022-10-07 09:01 UTC by rawen17

…functions

2022-10-08 06:24 UTC, chavacava requested changes
I've left some comments
Please fill the PR description by using the PR description template

In general I think regexps are too powerful (or complicated?) to be used without the risk of ignoring things you don't know you are ignoring. For example, the regexp `.Println` used in the tests will not ignore just "methods named `Println` of any package" but **also** any method or function named such as `Println` is a suffix of the name (`myPrintln`, `ThisIsAnotherPrintln`, `dPrintlln`, ...)

2022-10-08 06:24 UTC, chavacava commented on rule/add-constant.go
> +					for _, exclude := range strings.Split(excludes, ",") {
trimming blanks can help in avoiding subtle config problems.
For example configuring the rule with 
```go
"os.*,.Println,ignoredFunc"
```
will not behave as if it is configured with
```go
"os.*, .Println,ignoredFunc"
```

2022-10-13 10:31 UTC, chavacava commented
My point is that RE are very error prone (at the point that your own test case `.Println` was wrong)
I'm not against the use of RE and I agree that providing clear doc will help in avoiding subtle errors; for example in the rule documentation it should be interesting to highlight that `fmt.Println` in the given example, will make `revive` ignore `fmt.Println`, `fmtXPrintln`, `fmt1Println`, an so on.

2022-10-13 11:06 UTC, chavacava approved these changes

2022-10-13 11:23 UTC, merged

2022-10-13 11:26 UTC, chavacava commented
> It was my fault, i had to write regexp `os\\.*,fmt\\.Println,make` in documentation, but i wrote `os.*,fmt.Println,make ` I will fix it

@rawen17 thanks for the PR, I've already merged it. 
Sorry @xobotyi I did not notice that I was answering to you (and not to the author of the PR)

2022-10-13 11:29 UTC, rawen17 commented
@chavacava Ok, thanks, i will create new PR for this changes