nested-structs: show issue with "struct{}" detection
mgechev/revive pull request #828
Opened 2023-05-16 03:27 UTC by sbunce

Background
=========
This pull request is to demonstrate issue in https://github.com/mgechev/revive/issues/824

It seems like the intent is to not fail on "struct{}".

2023-05-19 21:03 UTC, mgechev approved these changes

2023-05-22 16:43 UTC, mgechev requested changes
Looks like this file contains broken syntax

2023-05-22 16:49 UTC, sbunce commented
The syntax is go generics.

I put it on go playground here.
https://go.dev/play/p/XSgqTLsjaS_N

I think the 1.17 test is failing because generics was introduced in go1.18.

2023-10-29 07:47 UTC, chavacava commented
Closing this PR. The example is already mentioned in #824 
Thanks!

2023-10-29 07:47 UTC, closed without merging